import { useState } from "react";
import { Share2, Download, Copy, Check, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";

interface Vehicle {
  manufacturer: string;
  model: string;
  year: number;
}

interface Message {
  role: "user" | "assistant";
  content: string;
  images?: string[];
}

interface MechanicSummaryProps {
  messages: Message[];
  vehicle: Vehicle | null;
  onClose: () => void;
}

const MechanicSummary = ({ messages, vehicle, onClose }: MechanicSummaryProps) => {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateSummary = () => {
    const userMessages = messages.filter((m) => m.role === "user");
    const assistantMessages = messages.filter((m) => m.role === "assistant");
    const hasImages = messages.some((m) => m.images && m.images.length > 0);

    let summary = "MECHANIC HANDOVER SUMMARY\n";
    summary += "Generated by After Brakes AI\n";
    summary += "─".repeat(40) + "\n\n";

    if (vehicle) {
      summary += "VEHICLE INFORMATION:\n";
      summary += `• ${vehicle.manufacturer} ${vehicle.model} (${vehicle.year})\n\n`;
    }

    summary += "REPORTED SYMPTOMS:\n";
    userMessages.slice(0, 3).forEach((msg) => {
      const shortContent = msg.content.length > 150 ? msg.content.slice(0, 150) + "..." : msg.content;
      summary += `• ${shortContent}\n`;
    });
    summary += "\n";

    if (hasImages) {
      summary += "IMAGES PROVIDED:\n";
      summary += `• ${messages.filter((m) => m.images?.length).reduce((acc, m) => acc + (m.images?.length || 0), 0)} image(s) shared for analysis\n\n`;
    }

    summary += "AI ANALYSIS & SUSPECTED CAUSES:\n";
    const lastAssistant = assistantMessages[assistantMessages.length - 1];
    if (lastAssistant) {
      const lines = lastAssistant.content.split("\n").filter((l) => l.trim());
      lines.slice(0, 5).forEach((line) => {
        const shortLine = line.length > 100 ? line.slice(0, 100) + "..." : line;
        summary += `• ${shortLine}\n`;
      });
    }
    summary += "\n";

    summary += "SUGGESTED CHECKS:\n";
    summary += "• Physical inspection of components mentioned above\n";
    summary += "• Diagnostic scan if applicable\n";
    summary += "• Verify symptoms match AI analysis\n\n";

    summary += "─".repeat(40) + "\n";
    summary += "NOTE: This summary is an AI-generated aid for discussion.\n";
    summary += "Final diagnosis should be made by a qualified mechanic.\n";

    return summary;
  };

  const summary = generateSummary();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    toast({ title: "Summary copied to clipboard" });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([summary], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `mechanic-summary-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Summary downloaded" });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm" onClick={onClose}>
      <div
        className="w-full max-w-lg mx-4 bg-card border border-border/40 rounded-2xl shadow-lg shadow-primary/10 p-4 animate-fade-slide-up max-h-[80vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Share2 className="w-5 h-5 text-primary" />
            <h3 className="text-lg font-semibold text-foreground">Mechanic Summary</h3>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8">
            <X className="w-4 h-4" />
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto mb-4">
          <pre className="text-sm text-muted-foreground whitespace-pre-wrap font-mono bg-secondary/30 p-4 rounded-xl border border-border/20">
            {summary}
          </pre>
        </div>

        <div className="flex gap-2">
          <Button onClick={handleCopy} className="flex-1 btn-glow">
            {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
            {copied ? "Copied!" : "Copy"}
          </Button>
          <Button onClick={handleDownload} variant="outline" className="flex-1 btn-glow">
            <Download className="w-4 h-4 mr-2" />
            Download
          </Button>
        </div>
      </div>
    </div>
  );
};

export default MechanicSummary;
